-- Price Log core schema.
-- Portable SQL: runs identically on H2 (dev) and PostgreSQL (prod).
-- Money is stored as integer cents. Unit prices keep decimals because they are derived.

CREATE TABLE store (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain      VARCHAR(32)  NOT NULL,
    label      VARCHAR(128) NOT NULL,
    city       VARCHAR(64),
    state      VARCHAR(8),
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX ux_store_chain_label ON store (chain, label);

CREATE TABLE product (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- Identifies one concrete SKU: brand + name + size. Two tags of the same
    -- item at different stores collapse onto the same row.
    normalized_key  VARCHAR(255) NOT NULL UNIQUE,
    -- Identifies a comparison group: category + quality attributes, no brand,
    -- no size. This is what "where are organic eggs cheapest" groups on.
    comparison_key  VARCHAR(255) NOT NULL,
    display_name    VARCHAR(255) NOT NULL,
    brand           VARCHAR(128),
    category        VARCHAR(48)  NOT NULL,
    size_value      NUMERIC(14, 4),
    size_unit       VARCHAR(16),
    pack_count      INT,
    -- Everything reduced to one canonical unit so prices are comparable:
    -- OZ for weight, FL_OZ for volume, COUNT for countable goods.
    base_unit       VARCHAR(16),
    base_quantity   NUMERIC(16, 4),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_product_comparison_key ON product (comparison_key);
CREATE INDEX ix_product_category ON product (category);

CREATE TABLE product_attribute (
    product_id BIGINT      NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    attribute  VARCHAR(48) NOT NULL,
    PRIMARY KEY (product_id, attribute)
);

CREATE TABLE price_observation (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id          BIGINT  NOT NULL REFERENCES product (id),
    store_id            BIGINT  NOT NULL REFERENCES store (id),
    observed_on         DATE    NOT NULL,

    -- What you would actually pay at the register today.
    price_cents         INT     NOT NULL,
    -- Pre-discount price when the tag shows one, else null.
    regular_price_cents INT,
    on_sale             BOOLEAN NOT NULL DEFAULT FALSE,
    -- REGULAR | INSTANT_SAVINGS | MANAGER_MARKDOWN | CLEARANCE | DISCONTINUED
    sale_signal         VARCHAR(32),
    sale_ends_on        DATE,
    -- Tag says the item is not being restocked (Costco asterisk, Sam's "C").
    discontinued        BOOLEAN NOT NULL DEFAULT FALSE,

    -- price_cents / product.base_quantity, in the product's base_unit.
    unit_price_cents    NUMERIC(14, 4),
    base_unit           VARCHAR(16),

    item_number         VARCHAR(32),
    photo_url           VARCHAR(512),
    confidence          NUMERIC(4, 3),
    -- Extraction lands here as unverified; the review screen clears this.
    needs_review        BOOLEAN NOT NULL DEFAULT TRUE,
    raw_extraction      TEXT,
    notes               VARCHAR(512),
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX ix_obs_product_date ON price_observation (product_id, observed_on DESC);
CREATE INDEX ix_obs_store_date ON price_observation (store_id, observed_on DESC);
CREATE INDEX ix_obs_needs_review ON price_observation (needs_review);

-- Store-specific price tag semantics, kept in data rather than code so the
-- rules can be corrected as they are learned without a redeploy.
CREATE TABLE tag_rule (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain      VARCHAR(32)  NOT NULL,
    -- PRICE_ENDING | MARKER | TEXT_CONTAINS
    match_type VARCHAR(32)  NOT NULL,
    pattern    VARCHAR(64)  NOT NULL,
    signal     VARCHAR(32)  NOT NULL,
    meaning    VARCHAR(255) NOT NULL,
    advice     VARCHAR(255),
    -- Lower number wins when several rules match one tag.
    priority   INT          NOT NULL DEFAULT 100,
    enabled    BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE INDEX ix_tag_rule_chain ON tag_rule (chain, enabled);
