-- Watchlist, price-change history, and externally published deals.

-- Items worth keeping an eye on, with an optional "tell me at this price".
ALTER TABLE product ADD COLUMN watched BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE product ADD COLUMN target_price_cents INT;

-- What this item cost the last time it was seen, captured at the moment of
-- the new sighting. Stored rather than recomputed so that showing "down $3.20
-- since June" on a list of fifty rows does not mean fifty extra queries, and
-- so the comparison stays true to what was known on the day.
ALTER TABLE price_observation ADD COLUMN previous_price_cents INT;
ALTER TABLE price_observation ADD COLUMN previous_observed_on DATE;
ALTER TABLE price_observation ADD COLUMN lowest_before_cents INT;

-- Promotions published by a retailer, matched to logged items by item number.
CREATE TABLE deal_sighting (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chain          VARCHAR(32)  NOT NULL,
    -- chain + item number + title, so re-reading the same promotion updates
    -- the existing row instead of piling up duplicates.
    fingerprint    VARCHAR(255) NOT NULL UNIQUE,
    item_number    VARCHAR(32),
    title          VARCHAR(512) NOT NULL,
    discount_cents INT,
    -- Costco marks each offer as warehouse, online, or both. Only the ones
    -- valid in the warehouse matter for someone standing in the warehouse.
    in_warehouse   BOOLEAN   DEFAULT TRUE NOT NULL,
    first_seen_on  DATE      NOT NULL,
    last_seen_on   DATE      NOT NULL,
    active         BOOLEAN   DEFAULT TRUE NOT NULL
);

CREATE INDEX ix_deal_item ON deal_sighting (item_number);
CREATE INDEX ix_deal_active ON deal_sighting (chain, active);

-- One row per source, so a failed fetch is visible rather than silent.
CREATE TABLE deal_refresh (
    chain           VARCHAR(32) PRIMARY KEY,
    last_attempt_at TIMESTAMP,
    last_success_at TIMESTAMP,
    last_error      VARCHAR(512),
    deals_found     INT
);
