-- User accounts. Everything the log records now belongs to someone: the
-- pre-accounts single user becomes the owner, and the legacy X-API-Key maps
-- to that row. Portable SQL: runs identically on H2 (dev) and PostgreSQL (prod).

CREATE TABLE app_user (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         VARCHAR(254) NOT NULL,
    password_hash VARCHAR(128),
    display_name  VARCHAR(128) NOT NULL,
    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX ux_app_user_email ON app_user (email);

-- The household that ran the single-user prototype. API-key traffic and
-- anonymous public reads keep acting as this row.
INSERT INTO app_user (email, display_name) VALUES ('owner@local', 'Owner');

ALTER TABLE store ADD COLUMN user_id BIGINT REFERENCES app_user (id);
ALTER TABLE price_observation ADD COLUMN user_id BIGINT REFERENCES app_user (id);
ALTER TABLE tag_rule ADD COLUMN user_id BIGINT REFERENCES app_user (id);

UPDATE store SET user_id = (SELECT MIN(id) FROM app_user);
UPDATE price_observation SET user_id = (SELECT MIN(id) FROM app_user);
UPDATE tag_rule SET user_id = (SELECT MIN(id) FROM app_user);

ALTER TABLE store ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE price_observation ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE tag_rule ALTER COLUMN user_id SET NOT NULL;

CREATE INDEX ix_store_user ON store (user_id);
CREATE INDEX ix_obs_user ON price_observation (user_id);
CREATE INDEX ix_tag_rule_user ON tag_rule (user_id);

-- The watchlist moves off the shared product row: one user's "watch this"
-- must never leak onto another user's view of the same SKU.
CREATE TABLE user_product_watch (
    user_id            BIGINT     NOT NULL REFERENCES app_user (id) ON DELETE CASCADE,
    product_id         BIGINT     NOT NULL REFERENCES product (id) ON DELETE CASCADE,
    watched            BOOLEAN    NOT NULL DEFAULT TRUE,
    target_price_cents INT,
    created_at         TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, product_id)
);

INSERT INTO user_product_watch (user_id, product_id, watched, target_price_cents)
SELECT (SELECT MIN(id) FROM app_user), id, watched, target_price_cents
FROM product
WHERE watched OR target_price_cents IS NOT NULL;

ALTER TABLE product DROP COLUMN watched;
ALTER TABLE product DROP COLUMN target_price_cents;

-- When a row was last touched, so sync and "recently changed" have something
-- to order by. Nullable: old rows predate the column.
ALTER TABLE store ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE price_observation ADD COLUMN updated_at TIMESTAMP;
